name: Build and Deploy Java Application into Tomcat Server on EC2 and run Code Analysis with Sonarqube

on:
  push:
    branches: [ "production-main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install -f SampleWebApp/pom.xml

    - name: Run Unit Tests
      run: mvn test -f SampleWebApp/pom.xml

    - name: SonarQube Analysis Scan 
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}  
        run: |
          mvn -f SampleWebApp/pom.xml \
            org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=SampleWebApp \
            -Dsonar.host.url=${SONAR_HOST_URL} \
            -Dsonar.login=${SONAR_TOKEN}

    - name: Upload WAR Artifact
      uses: actions/upload-artifact@v4
      with:
        name: SampleWebApp-war
        path: SampleWebApp/target/SampleWebApp.war

    - name: Deploy to Tomcat
      run: |
        echo "Deploying a WAR file to Tomcat on EC2 instance..."
        curl -v -u "${{ secrets.TOMCAT_USER }}:${{ secrets.TOMCAT_PASSWORD }}" \
        -T SampleWebApp/target/SampleWebApp.war \
        "http://${{ secrets.TOMCAT_HOST }}/manager/text/deploy?path=/SampleWebApp&update=true"
